project_id = "fjvvnnvvgaszjdcstcaj"

[functions.send-contact-notification]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-low-stock-alert]
verify_jwt = false

[functions.send-order-alert]
verify_jwt = false

[functions.product-color-image]
verify_jwt = false

[functions.phonepe-payment]
verify_jwt = false
